// ---- issues ----
export const FETCH_ISSUES_BY_OWNER_AND_REPO = 'FETCH_ISSUES_BY_OWNER_AND_REPO';
export const SET_ISSUES_ARRAY_AS_OBJECT = 'SET_ISSUES_ARRAY_AS_OBJECT';
export const ADD_NEW_ISSUE = 'ADD_NEW_ISSUE';
export const UPDATE_ISSUE_BODY = 'UPDATE_ISSUE_BODY';

// ---- ui ----
export const SET_CURRENT_ISSUE_ID = 'SET_CURRENT_ISSUE_ID';
export const ON_CHANGE_FILTER_ISSUES_INPUT = 'ON_CHANGE_FILTER_ISSUES_INPUT';
